name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_K8S_STORAGE_WR }}
        export_default_credentials: true

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.REGISTRY_REGION }}-docker.pkg.dev --quiet

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_NAME }}/api:latest api/
        docker build -t ${{ secrets.REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_NAME }}/worker:latest worker/
        docker push ${{ secrets.REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_NAME }}/api:latest
        docker push ${{ secrets.REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_NAME }}/worker:latest

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.REGISTRY_REGION }}
        envsubst < k8s/overlays/kustomization.tmpl.yaml > k8s/overlays/kustomization.yaml
        kubectl kustomize k8s/overlays/test | kubectl apply -f -
